# Generated by Django 2.2 on 2020-10-21 12:07

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20201021_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=tinymce.models.HTMLField(),
        ),
    ]
